### PR TITLE
Feature/plex settings

### PR DESCRIPTION
**Pull request by ZeroCoolGOS**
Most of these changes should not impact any of the existing working system.

Plex Move Poster Display - Admin Replacement

Changes:
- Separate the admin and Login page into their designated pages and mimic the Plex web portal theme
- Add support for Exporting and Importing configuration files.
- Simply duplicate code by moving to separate php and js files and calling the functions.
- Move business logic into assets folder.
- Update the header to use the same php business logic that the settings pages are using.
- Add check to see if Plex Token is defined.  If the token does not exist then it will go to the 'general' config page, and if not logged in it will prompt you to login.
- Update to fix incorrect documentation
- Add 'settings' option to Dockerfile
- Update display version number
- Update how the cache folders are handled. Remove placeholder files if they exist.

Known Issues:
- Color picker now displaying correctly.  Hidden behind background.

ToDo:
- Fix known issues
- Review minor cosmetic issues
- Add 'Release Notes'
- Update to have this version moved programmatically. GitVersion is ideal.

### CODE REVIEW

**Comment by MattsShack** [comment]
I committed this, however there is a few features broken (Example: Show Plex Token).

Also we will need to change the theme, remove the Plex logo at the top, and add a footer with all the trademark information / links to Plex. I do not want to get in trouble with Plex.

**Comment by ZeroCoolGOS** [comment]
Ok, I will look at changing the theme.  The main focus of what I had done was to to fully match Plex in color scheme to make it feel just like how plex is.

I will also look into the footer, and will get this addressed this week.

I have not seen an issue with the "Show/Hide" for plex token.  What is the issue your having with it?

Also I don't think you would get in trouble with Plex, but I can understand your concern and will address this.

**Comment by MattsShack** [comment]
Thank you for more great great additions! I really like what you have done.

Okay, I think we keep the theme :) , remove the Plex logo at the top, and add the footer.  
Let me do  some more testing on the Show/Hide...

**Comment by ZeroCoolGOS** [comment]
Will do.

Working on it now.

How would you like the footer?  I am looking at the original admin page and there is no footer in regards to plex.

**Comment by ZeroCoolGOS** [comment]
And I think I found the issue with the show/hide.

I will have a fix ready in about 15 min.

**Pull request merged**
