### PR TITLE
v2.10.6 Community Updates

### PR DESCRIPTION
**Pull request by ZeroCoolGOS**
Enhancement - Digital Picture Frame Mode (Issue #48)
- Update image upload to support Zip files and sub-folders
- Adjust 'Background Art' logic checkbox to set the image as a 'Full Screen' image.
- Disable 'blur' for background image when 'Background Art' is selected for custom configuration.
- Update custom image select to support sub-folders

Updates and Bug Fixes:
- Attempt to address an issue that users are experiencing when upgrading from 2.10.4 to 2.10.5.  Possible issue around how the refresh system as implemented and an adjustment for that now has been done.  Recreation unsuccessful. (Issue #27 Issue #56)
- Minor adjustments to the backend as discovered when working on Issue #48

### CODE REVIEW

**Comment by titelies** [comment]
No issues updating to 2.10.6 @ZeroCoolGOS

**Comment by ZeroCoolGOS** [comment]
@titelies 

Is that coming from 2.10.4 or 2.10.5?

**Comment by titelies** [comment]
From 2.10.5 config export after having manually entered all the info again

**Comment by ZeroCoolGOS** [comment]
@titelies 

Cool.  Thanks for letting me know.

I am working on a new update (hopefully in the next day or two) that has a bunch more changes for the config file, and I am hoping that it wont brake any backwards compatibility, but there are a bunch of cleanup that needs to be done for some future features.

**Pull request merged**
