### PR TITLE
v2.10.5 Community Updates

### PR DESCRIPTION
**Pull request by ZeroCoolGOS**
Enhancement - Font Enhancements (Issue #44)
- Add Fix for when font = None that it defaults back to system font not generic font.

Enhancement - Digital Picture Frame Mode (Issue #48)
- Separate timer to give timer to each one of the types of display options.
- Cleanup javascript to use switch case vs. if statement to better organize load options, and to allow for future data promotion to the front end.
- Update to how the index page takes in changes to refresh time. Previously if a refresh time was set and you load index page that refresh was locked in until you did a full page reload. Now, if refresh is adjusted the page will validate and if the current and new refresh times are out of sync the page will do a full reload
- Add some hooks for Digital picture frame to disable CSS blur

ToDo:
- Look into moving index JavaScripts to dedicated js file for better reuse of functions as a good portion are duplicated.

Known Bugs:
- For page refresh if out of sync there may be a poster flash/skip as its loading the new 'session'

Updates and Bug Fixes:
- Disable frontend for 'Poster Transition/Refresh Speed' and 'Bottom Scrolling Text' options in the 'Common Configuration' page as these options are now available as individuals for the 'Coming Soon' and 'Now Showing' pages.
- Add more Plex API metadata read. Collecting content rating and if nowPlaying is directplay or transcode, also getting information on video and audio codecs.
- Update log system to better organize logs. First isolate PLEXLib logs to PLEX isolated log files.

### CODE REVIEW

**Comment by titelies** [comment]
Black screen only after Restoring saved Config to 2.10.5 and Reboot.

**Comment by ZeroCoolGOS** [comment]
@titelies is the black screen on the config page or the index.php?

**Comment by titelies** [comment]
Black screen was on the index page after restoring my saved configuration page and a reboot. Just went back to 2.10.4

**Comment by ZeroCoolGOS** [comment]
Sorry to hear that.  I have not been able to recreate the issue yet.

**Comment by titelies** [comment]
I'll try again. but I do the same thing when updating. Giving it another go to 2.10.5.

**Comment by ZeroCoolGOS** [comment]
You should not need to reboot.

You may also want to go into the "Now Showing" and "Coming Soon" and set the timer.

**Comment by titelies** [comment]
The reboot is how I get Chromium into kiosk mode. 2.10.5 black screen again, made sure to set timers on Coming Soon and Now Showing after importing config from 2.10.4.  
My steps are as follows: 
cd /home/pi/Documents
sudo git clone --branch dev https://github.com/MattsShack/Plex-Movie-Poster-Display.git
cd Plex-Movie-Poster-Display
sudo cp -R * /var/www/html
I load up the config page and restore my saved 2.10.4 config, logout and login with my own credentials, 
this time I added the timers to the Now Showing and Coming Soon.
Saved and rebooted TV display into kiosk mode to a black screen...

**Comment by ZeroCoolGOS** [comment]
Hmm. that is odd.  And those are the steps you have done during the last upgrade?

to help speed up that process a bit.
You don't need to keep doing a git clone.  you can just cd into your Plex-Movie-Poster-Display and do "sudo git pull".  That should just pull down the latest from that branch your already set to.

I will try and recreate your issue on one of my Pi's shortly.

**Comment by ZeroCoolGOS** [comment]
I have just tested on a Pi and I was not able to recreate.

Can you also try to see if the security permissions are set too?
sudo chmod -R 774 /var/www/html/
sudo chown -R pi:www-data /var/www/html/

Also can you check to see if your fonts are uploaded?

If you get  a black screen that usually means that some data is missing as its trying to process the data.

Once we isolate the issue I can work on a fix so that it can hopefully be avoided in the future.

**Comment by titelies** [comment]
Fonts are in the Cache > Fonts folder, all seems well. Went back to 2.10.4 without issue.
Appreciate the sudo git pull advice, just not sure what that will look like. Currently, I like to keep all the sudo git clones in my Docs folder, I just rename them 10-2, 10-3, 10-4 before I do a new sudo git clone so I can always revert back if need be to an older version.

**Comment by ZeroCoolGOS** [comment]
When you have some time to help us debug, can you provide a copy of your config file that you are restoring (minus the secure data)?

I will look into trying to collect more data on my end that in the next release may help out.

No rush as your system is working with 2.10.4.

I will have 2.10.6 in the next couple days.

**Comment by titelies** [comment]
Absolutely.  
[PMP_config_copy.zip](https://github.com/MattsShack/Plex-Movie-Poster-Display/files/6174757/PMP_config_copy.zip)

**Comment by titelies** [comment]
@ZeroCoolGOS Woke up this morning and decided to copy 2.10.5 but not import my saved config. Reentered all the info and everything is back to normal with 2.10.5 and I have Exported a new Configuration file.

**Comment by ZeroCoolGOS** [comment]
Interesting. I will also compare the old config file you provided so I can try and find the glitch. 

Glad you where able to get it going.

**Pull request merged**
